#!/usr/bin/env python

# This script reads from stdin or from a list of files passed as params
# and searches for i18n phrases, by looking for places where __("blah blah")
# exist. Then it renders a single column csv of these phrases to stdout.

import fileinput
import re
import sys

text = ''.join([l.strip() for l in fileinput.input()])

result = re.findall("__\(['\"]([^'\"]*)['\"]\)", text, re.DOTALL)

if not result:
    sys.exit(0)

for r in result:
    print '"%s",' % r
